"""Bash completion for the `buseval` command.

The first run writes the completion file where bash-completion already looks.
`~/.bashrc` is left unchanged. Directories that need administrator rights
are not used.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

_FILE_DESTS = frozenset({"output", "topology", "measurement", "perf_text", "dbc", "GMSL"})
_SAFE_NAME = re.compile(r"^[A-Za-z0-9._+-]+$")


def command_name() -> str:
    """Basename of the command being run. Tests and `python -m` stay `buseval`."""
    name = Path(sys.argv[0]).name
    if (
        name.endswith(".py")
        or re.fullmatch(r"python[\d.]*", name)
        or name in {"pytest", "py.test"}
        or not _SAFE_NAME.fullmatch(name)
    ):
        return "buseval"
    return name


def completion_dir() -> Path:
    """Directory bash reads on Tab, skipping system locations.

    `BASH_COMPLETION_USER_DIR` is first, then `XDG_DATA_HOME`, then
    `~/.local/share`. A colon-separated user dir uses its first entry,
    the same way bash-completion does.
    """
    override = os.environ.get("BUSEVAL_COMPLETION_DIR")
    if override:
        return Path(override)
    user_dir = os.environ.get("BASH_COMPLETION_USER_DIR", "")
    first = next((part for part in user_dir.split(":") if part), "")
    if first:
        return Path(first) / "completions"
    data_home = os.environ.get("XDG_DATA_HOME")
    base = Path(data_home) if data_home else Path.home() / ".local" / "share"
    return base / "bash-completion" / "completions"


def install_shell_completion() -> None:
    """Write the completion file when it is missing or out of date."""
    try:
        command = command_name()
        text = completion_script(command)
        directory = completion_dir()
        path = directory / command
        if path.is_file() and path.read_text(encoding="utf-8") == text:
            return
        directory.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    except OSError:
        return


def completion_script(command: str | None = None) -> str:
    from .cli import _list_presets, build_parser

    command = command or command_name()
    function = "_" + re.sub(r"[^A-Za-z0-9_]", "_", command)
    parser = build_parser()
    commands = _subcommands(parser)
    file_flags: list[str] = []
    choice_flags: list[tuple[str, list[str]]] = []
    value_flags: list[str] = []
    per_command: list[tuple[str, list[str], list[str]]] = []

    for name, sub in commands.items():
        flags = ["--help"]
        positionals: list[str] = []
        for action in sub._actions:
            if not action.option_strings:
                if action.choices:
                    positionals.extend(str(item) for item in action.choices)
                continue
            flags.extend(action.option_strings)
            if action.dest == "soc":
                choice_flags.append((" ".join(action.option_strings), _list_presets()))
            elif action.choices:
                choice_flags.append((" ".join(action.option_strings), [str(item) for item in action.choices]))
            elif action.dest in _FILE_DESTS:
                file_flags.extend(action.option_strings)
            elif _takes_value(action):
                value_flags.extend(action.option_strings)
        per_command.append((name, _unique(flags), positionals))

    root_flags = ["--help", "--version"]
    lines = [
        "# Generated by buseval. Bash loads this file on Tab.",
        f"{function}() {{",
        "    local cur prev cmd",
        "    COMPREPLY=()",
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        '    prev="${COMP_WORDS[COMP_CWORD-1]}"',
        '    cmd=""',
        "    local i",
        "    for ((i=1; i<COMP_CWORD; i++)); do",
        '        case "${COMP_WORDS[i]}" in',
        "            -*) ;;",
        '            *) cmd="${COMP_WORDS[i]}"; break ;;',
        "        esac",
        "    done",
        "    case \"$prev\" in",
        f"        {_pattern(file_flags)})",
        "            COMPREPLY=( $(compgen -f -- \"$cur\") )",
        "            compopt -o filenames 2>/dev/null || true",
        "            return",
        "            ;;",
    ]
    for flags, choices in choice_flags:
        lines.append(f"        {_pattern(flags.split())})")
        lines.append(f'            COMPREPLY=( $(compgen -W "{_words(choices)}" -- "$cur") )')
        lines.append("            return")
        lines.append("            ;;")
    if value_flags:
        lines.append(f"        {_pattern(value_flags)})")
        lines.append("            return")
        lines.append("            ;;")
    lines.append("    esac")
    lines.append("    case \"$cmd\" in")
    for name, flags, positionals in per_command:
        lines.append(f"        {name})")
        if positionals:
            lines.append('            if [[ "$cur" == -* ]]; then')
            lines.append(f'                COMPREPLY=( $(compgen -W "{_words(flags)}" -- "$cur") )')
            lines.append("            else")
            lines.append(f'                COMPREPLY=( $(compgen -W "{_words(positionals)}" -- "$cur") )')
            lines.append("            fi")
        else:
            lines.append(f'            COMPREPLY=( $(compgen -W "{_words(flags)}" -- "$cur") )')
        lines.append("            ;;")
    lines.append("        *)")
    lines.append(
        f'            COMPREPLY=( $(compgen -W "{_words([*commands, *root_flags])}" -- "$cur") )'
    )
    lines.append("            ;;")
    lines.append("    esac")
    lines.append("}")
    lines.append(f"complete -F {function} {command}")
    lines.append("")
    return "\n".join(lines)


def _subcommands(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    return {}


def _takes_value(action: argparse.Action) -> bool:
    return not isinstance(
        action,
        (argparse._StoreTrueAction, argparse._StoreFalseAction, argparse._HelpAction, argparse._VersionAction),
    )


def _unique(items: list[str]) -> list[str]:
    seen: list[str] = []
    for item in items:
        if item not in seen:
            seen.append(item)
    return seen


def _words(items: list[str]) -> str:
    return " ".join(items)


def _pattern(flags: list[str]) -> str:
    return "|".join(_unique(flags))
